### PR TITLE
Users

### PR DESCRIPTION
**Pull request by chadwcarlson**

### CODE REVIEW

**Comment by Avamander** [comment]
Are you having trouble running this with new NodeJS or was the pull request an accident in general?

**Comment by chadwcarlson** [comment]
Oh hey there. It was an accident actually.  I'm trying to troubleshoot this atm however. When players make moves, its fails to update the board/switch turns with this generic error.

`PUT request returned error: error ()`

Happy to open an issue if that's preferred.

**Comment by Avamander** [comment]
I think I fixed it by patching icebox.js here: https://github.com/Avamander/html-scrabble/blob/master/client/javascript/icebox.js#L101

**Comment by Avamander** [comment]
I don't know what's actually preferred :D I just suspected I wasn't the only one stumbling upon the issue and you might want to know.

**Comment by chadwcarlson** [comment]
Well hot dawg. that did fix it. Thank ya friend! Stay safe out there!

**Comment by hanshuebner** [comment]
@Avamander Thanks for chiming in.  Can you open a PR for your change to benefit the next person?  There seems to be a (very small) spike in interest in this project.

**Comment by Avamander** [comment]
@hanshuebner `icebox.js` is a symlink in this repo, I'm not sure where it's actually located. Maybe you could perform the fix?

**Comment by hanshuebner** [comment]
icebox.js lives at the top-level of the repository and the symbolic link in `client/javascript/` correctly points there.  @Avamander What is the problem with it exactly?

**Comment by Avamander** [comment]
It was a month ago when I fixed it. If I remember correctly the issue was that not having a constructor made icepack.js crash, this might be a change in new JS, falling back to `null` in the cases where there's no constructor fixes the issue. The line here, https://github.com/Avamander/html-scrabble/blob/master/client/javascript/icebox.js#L101 fixes it if I remember correctly.

**Comment by hanshuebner** [comment]
@Avamander icebox.js is no longer pulled from npm but instead included with html-scrabble, and the fix is already there.

**Pull request closed without merging**
