### PR TITLE
Add spanish support

### PR DESCRIPTION
**Pull request by plorenzatto**
This PR adds spanish support using letter distributions from wikipedia.

Ref:
https://en.wikipedia.org/wiki/Scrabble_letter_distributions#Spanish

### CODE REVIEW

**Comment by hanshuebner** [comment]
How do the double-letter glyphs display on the board?  How are they entered on the keyboard?  I have rejected other pull requests because I thought the game cannot deal with them, but maybe I'm wrong?

**Comment by plorenzatto** [comment]
I haven't tried to use double glyph wild cards.

The score number fails to show in double glyph tiles:

Selection_051

What would be a good fix for this issues?

**Comment by hanshuebner** [comment]
I think this could be fixed by investigating how letters and the letter score is rendered and maybe using a different CSS class with a smaller font for double-glyph letters.  I'm not sure about the wildcards either, as I don't know how these letters are typed on the keyboard.

This requires spending some time with the source code to devise a viable solution and implement it.  I'm open to merging a patch, but I don't want to justr include letter sets that are basically unplayable.

**Comment by plorenzatto** [comment]
I changed the CSS a bit and got to this:

Selection_053

Do you think it's good enough?

Regarding the wildcard for double glyph in spanish/latam keyboards CH, RR and LL are not present so they are typed as two distinct characters.
Because of that I think that the way to go is to show the player a combo with the list of legal letters to choose from whether they are single or double glyph ones.

**Comment by hanshuebner** [comment]
I would like the one-letter tiles to retain their font size and positioning, so please make it so that the CSS is different for two-letter tiles.

With respect to the wild card:  Currently, the letter for the wild card is chosen by typing it on the keyboard.  If you want to add a panel of all tiles so that the user can choose from that, please retain the current functionality (keyboard input).

Most of the time, I type the words that I want to place from the keyboard.  In that usage mode, whenever I type a letter that I don't have, but there is a blank on my bench, the UI automatically uses the blank and assigns the letter that I have typed.  That usage mode will certainly not work with the double-letter tiles, or at least it will require some thought to completely work.

Thanks! Hans

**Comment by Avamander** [comment]
Just mentioning just in case someone actually starts revamping the blank UI - it would be nice if mobile device support were also considered. Right now I got touch support to the game with jQuery UI Touch Punch (http://touchpunch.furf.com/) and it's nicely playable, but blanks are still a bit annoying.

**Pull request closed without merging**
